### ISSUE TITLE
Need Comprehensive Tutorial

### ISSUE THREAD

**Issue by putuoka** [AnimMouse/SOCKS5-proxy-actions#1]
do you have a more detailed tutorial because I find it difficult to understand and when I try it doesn't work?

**Comment by AnimMouse** [comment]
Sorry for not having a comprehensive tutorial for this, since this is just a proof of concept for the 2021 GitHub Actions Hackathon on dev.to, and sadly, this repository lost, so I haven't taken care of this repository ever since.
Since you have something to do with this repository, I will try to maintain this repo, and will make a detailed tutorial for this.

**Comment by AnimMouse** [comment]
This workflow is now deprecated as this is getting hard to maintain, you can use my new program [AnimMouse/SOCKS5-Proxy-Codespaces](https://github.com/AnimMouse/SOCKS5-Proxy-Codespaces) instead.
